// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naozlzywijzybpihxote.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hb3psenl3aWp6eWJwaWh4b3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTk4NDksImV4cCI6MjA2MTgzNTg0OX0.p0S0ZSQ00kd7TLUhqrvVAfvUHfAYj4pzFlEXT53FR64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);